version: '3'
services:
  calculator:
    build: ./calculator
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - distributed-systems-project
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - distributed-systems-project
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - distributed-systems-project
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - distributed-systems-project
  gateway:
    build: ./gateway
    ports:
      - 8000:8000
    networks:
      - distributed-systems-project

networks:
  distributed-systems-project:
    driver: bridge